version: "3.8"
services:

  postgres-ji:
    image: postgres:13
    container_name: postgres-ji
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - base
  keycloak-server:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak-server
    volumes:
      - ./imports/keycloak/init:/opt/keycloak/data/import
      - ./imports/keycloak/mytheme:/opt/keycloak/themes/mytheme
    env_file:
      - .env
    ports:
      - "8001:8080"
    command: >
      start-dev 
      --hostname-strict=false 
      --db=postgres 
      --db-url=jdbc:postgresql://postgres-ji:5432/identity
      --db-username=jiapi 
      --db-password=jiapi@123 
      --import-realm
    networks:
      - base
    depends_on:
      postgres-ji:
        condition: service_healthy

  identity-service:
    container_name: identity-service
    image: pcs/identity-service:1.2-SNAPSHOT
    depends_on:
      - keycloak-server
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8002"
    networks:
      - base

networks:
  base:
    name: ji-network
    driver: bridge
    external: false